export type AdultSite = {
  id: string;
  name: string;
  url: string;
  description: string;
};

export const ADULT_SITES: AdultSite[] = [
  { id: '1', name: 'Pornhub', url: 'https://www.pornhub.com', description: 'One of the largest global adult video platforms.' },
  { id: '2', name: 'XVideos', url: 'https://www.xvideos.com', description: 'Massive catalog with frequent uploads and tags.' },
  { id: '3', name: 'XNXX', url: 'https://www.xnxx.com', description: 'Popular index of user-submitted adult videos.' },
  { id: '4', name: 'RedTube', url: 'https://www.redtube.com', description: 'Long-running streaming platform for adult content.' },
  { id: '5', name: 'YouPorn', url: 'https://www.youporn.com', description: 'Established adult site with curated channels.' },
  { id: '6', name: 'Tube8', url: 'https://www.tube8.com', description: 'Free-streaming adult site with mixed categories.' },
  { id: '7', name: 'SpankBang', url: 'https://www.spankbang.com', description: 'Fast UI and wide content variety for mature users.' },
  { id: '8', name: 'xHamster', url: 'https://xhamster.com', description: 'Large adult network with clips and creator profiles.' },
  { id: '9', name: 'TNAFlix', url: 'https://www.tnaflix.com', description: 'Classic tube-style site focused on free content.' },
  { id: '10', name: 'SunPorno', url: 'https://www.sunporno.com', description: 'Collection of trending adult scenes and shorts.' },
  { id: '11', name: 'HQPorner', url: 'https://hqporner.com', description: 'Emphasis on HD uploads and simple navigation.' },
  { id: '12', name: 'DrTuber', url: 'https://www.drtuber.com', description: 'Veteran adult portal with broad genre listing.' },
  { id: '13', name: 'Beeg', url: 'https://beeg.com', description: 'Minimalist interface and high-volume clip archive.' },
  { id: '14', name: 'Porn300', url: 'https://www.porn300.com', description: 'Large free index with genre-based browsing.' },
  { id: '15', name: 'Fapello', url: 'https://fapello.com', description: 'Trending 18+ media index and creator-related pages.' },
  { id: '16', name: 'Eporner', url: 'https://www.eporner.com', description: 'Community-driven uploads with category filters.' },
  { id: '17', name: 'HClips', url: 'https://www.hclips.com', description: 'Clip-first experience with classic adult tags.' },
  { id: '18', name: 'KeezMovies', url: 'https://www.keezmovies.com', description: 'Tube portal with free scenes and channels.' },
  { id: '19', name: 'PornTrex', url: 'https://www.porntrex.com', description: 'Indexing-style catalog with many sources.' },
  { id: '20', name: 'Motherless', url: 'https://motherless.com', description: 'Community-based 18+ content sharing platform.' },
  { id: '21', name: 'NudeVista', url: 'https://www.nudevista.com', description: 'Adult search engine across multiple tube sites.' },
  { id: '22', name: 'ThisVid', url: 'https://thisvid.com', description: 'Video community with profile and playlist features.' },
  { id: '23', name: 'DaftSex', url: 'https://daft.sex', description: 'Compact adult video portal with quick discovery.' },
  { id: '24', name: 'AnySex', url: 'https://anysex.com', description: 'General-purpose mature streaming catalog.' },
  { id: '25', name: 'SexVid', url: 'https://sexvid.xxx', description: 'Tube-style listing of free adult video clips.' },
  { id: '26', name: 'Pornhat', url: 'https://www.pornhat.com', description: 'Trending feed and category-heavy navigation.' },
  { id: '27', name: 'Vporn', url: 'https://www.vporn.com', description: 'Large searchable archive with tag filters.' },
  { id: '28', name: 'TubeGalore', url: 'https://www.tubegalore.com', description: 'Aggregator connecting many external adult sources.' },
  { id: '29', name: 'YesPornPlease', url: 'https://yespornplease.com', description: 'Curated embeds and scene indexing collection.' },
  { id: '30', name: 'PornOne', url: 'https://pornone.com', description: 'Search-driven adult catalog and feed pages.' },
  { id: '31', name: 'Slutload', url: 'https://www.slutload.com', description: 'Longstanding free-video adult website.' },
  { id: '32', name: '4Tube', url: 'https://www.4tube.com', description: 'Known adult platform with creator channels.' },
  { id: '33', name: 'Hardsextube', url: 'https://hardsextube.com', description: 'Genre-centric adult clips with simple layout.' },
  { id: '34', name: 'GotPorn', url: 'https://www.gotporn.com', description: 'Hub for free scenes from different networks.' },
  { id: '35', name: 'PornMD', url: 'https://pornmd.com', description: 'Adult search and trend analytics style portal.' },
  { id: '36', name: 'AlohaTube', url: 'https://www.alohatube.com', description: 'International tube site with broad categories.' },
  { id: '37', name: 'PornDish', url: 'https://www.porndish.com', description: 'Classic adult index focused on recent clips.' },
  { id: '38', name: 'PornBurst', url: 'https://www.pornburst.xxx', description: 'Collection of trending adult scene embeds.' },
  { id: '39', name: 'PornDig', url: 'https://www.porndig.com', description: 'Directory-style browsing of popular content.' },
  { id: '40', name: 'Cumlouder', url: 'https://www.cumlouder.com', description: 'High-production adult scenes and previews.' },
  { id: '41', name: 'Fux', url: 'https://www.fux.com', description: 'Simple tube-like website for mature audiences.' },
  { id: '42', name: 'PornCZ', url: 'https://www.porncz.com', description: 'Regional adult index with assorted categories.' },
  { id: '43', name: 'PornRips', url: 'https://www.pornrips.to', description: 'Aggregated scene listings and search pages.' },
  { id: '44', name: 'Playvids', url: 'https://www.playvids.com', description: 'Large adult video feed with profile support.' },
  { id: '45', name: 'Upornia', url: 'https://www.upornia.com', description: 'Categorized mature clips and quick filters.' },
  { id: '46', name: 'Porn.com', url: 'https://www.porn.com', description: 'Brand-domain adult portal with mixed content.' },
  { id: '47', name: 'Xbabe', url: 'https://www.xbabe.com', description: 'Adult clips portal oriented around trending tags.' },
  { id: '48', name: 'XFreeHD', url: 'https://www.xfreehd.com', description: 'High-definition clip library for adult viewers.' },
  { id: '49', name: 'TokyoMotion', url: 'https://www.tokyomotion.net', description: 'Video-sharing site often used for 18+ uploads.' },
  { id: '50', name: 'Nuvid', url: 'https://www.nuvid.com', description: 'Free-streaming adult archive with many tags.' },
  { id: '51', name: 'FreeOnes', url: 'https://www.freeones.com', description: 'Performer database and adult media links.' },
  { id: '52', name: 'Iwara', url: 'https://www.iwara.tv', description: 'Animation-heavy video platform with mature sections.' },
  { id: '53', name: 'Rule34Video', url: 'https://rule34video.com', description: 'Adult animation-oriented streaming collection.' },
  { id: '54', name: 'Erome', url: 'https://www.erome.com', description: 'Community gallery platform with mature uploads.' },
  { id: '55', name: 'ManyVids', url: 'https://www.manyvids.com', description: 'Creator monetization platform for adult media.' },
  { id: '56', name: 'Fansly', url: 'https://fansly.com', description: 'Subscription-based creator platform for 18+ content.' },
  { id: '57', name: 'OnlyFans', url: 'https://onlyfans.com', description: 'Subscription content platform used by adult creators.' },
  { id: '58', name: 'LoyalFans', url: 'https://www.loyalfans.com', description: 'Membership site for premium creator content.' },
  { id: '59', name: 'AdultTime', url: 'https://www.adulttime.com', description: 'Premium network with studio-backed releases.' },
  { id: '60', name: 'Brazzers', url: 'https://www.brazzers.com', description: 'Well-known premium studio network.' },
  { id: '61', name: 'Reality Kings', url: 'https://www.realitykings.com', description: 'Studio site focused on scene-based content.' },
  { id: '62', name: 'Naughty America', url: 'https://www.naughtyamerica.com', description: 'Premium platform with serialized site brands.' },
  { id: '63', name: 'BangBros', url: 'https://www.bangbros.com', description: 'Established producer with paid streaming access.' },
  { id: '64', name: 'Vixen', url: 'https://www.vixen.com', description: 'High-end adult production house platform.' },
  { id: '65', name: 'Blacked', url: 'https://www.blacked.com', description: 'Studio site recognized for cinematic production.' },
  { id: '66', name: 'Tushy', url: 'https://www.tushy.com', description: 'Premium subscription site in the Vixen network.' },
  { id: '67', name: 'Deeper', url: 'https://www.deeper.com', description: 'Boutique studio with premium scene releases.' },
  { id: '68', name: 'Digital Playground', url: 'https://www.digitalplayground.com', description: 'Long-running premium studio catalog.' },
  { id: '69', name: 'Evil Angel', url: 'https://www.evilangel.com', description: 'Studio publisher with extensive title archive.' },
  { id: '70', name: 'Jules Jordan', url: 'https://www.julesjordan.com', description: 'Producer website with paid scene access.' },
  { id: '71', name: 'Team Skeet', url: 'https://www.teamskeet.com', description: 'Network of niche branded premium sites.' },
  { id: '72', name: 'Mofos', url: 'https://www.mofos.com', description: 'Mainstream premium content network.' },
  { id: '73', name: 'Fake Hub', url: 'https://www.fakehub.com', description: 'Studio label network with scripted scenes.' },
  { id: '74', name: 'Private', url: 'https://www.private.com', description: 'Classic European studio with premium access.' },
  { id: '75', name: 'Legal Porno', url: 'https://www.legalporno.com', description: 'Premium studio site with specialized content.' },
  { id: '76', name: 'Kink', url: 'https://www.kink.com', description: 'Adult network for niche premium productions.' },
  { id: '77', name: 'MetArt', url: 'https://www.metart.com', description: 'Art-focused adult photo and video subscription site.' },
  { id: '78', name: 'Nubiles', url: 'https://nubiles.net', description: 'Premium network featuring multiple branded sites.' },
  { id: '79', name: 'Babes', url: 'https://www.babes.com', description: 'Curated premium scenes with polished visuals.' },
  { id: '80', name: 'Twistys', url: 'https://www.twistys.com', description: 'Subscription service with long-form scene content.' },
  { id: '81', name: 'Penthouse Gold', url: 'https://penthousegold.com', description: 'Legacy brand with premium digital content.' },
  { id: '82', name: 'Hustler', url: 'https://www.hustler.com', description: 'Magazine and media brand with adult offerings.' },
  { id: '83', name: 'Stripchat', url: 'https://stripchat.com', description: 'Live cam platform for adult audiences.' },
  { id: '84', name: 'Chaturbate', url: 'https://chaturbate.com', description: 'Popular live-stream cam community platform.' },
];
